fcmtoken calling sequence fixed (code line from 275 to 315)
Growthfilev2/frontend pull request #73
Opened 2021-01-06 05:59 UTC by adityadigant

2021-01-06 07:30 UTC, shikhar0507 commented on src/js/init.js
> +        }, geopoint);
In `requestCreator` func first param is the function name that is defined in `apiHandler.js` , second is the body to pass to the webworker (apihandler), third is the geopoint. Third param is used for `create`, `post` & `put` request 
because these requests accept geopoint of device. 

```
 return requestCreator('fcmToken', {
          token: _native.getFCMToken()
        }, geopoint);
``` Third param is not required.

Since this code block will run if token is present , it needs to pass the geopoint taken from above to the handleCheckin function.

2021-01-06 07:35 UTC, shikhar0507 commented on src/js/init.js
> +        }, geopoint);
Current code will not send geopoint  to the handleCheckin function. Just like here you are sending geopoint in Promise.resolve
``` 
if (appKey.getMode() === 'dev' && window.location.hostname === 'localhost') {
          return Promise.resolve(geopoint);
} 
``` 
To build in dev, make the requestCreator function return Promise.resolve  for every request. 
and comment out the dev,localhost and null conditions . so that  ```  return requestCreator('fcmToken', {
          token: _native.getFCMToken()
``` will run . Then think if this request success how you can send the geoopint from above

2021-01-06 07:36 UTC, shikhar0507 commented on src/js/init.js
>          handleCheckin(geopoint);
does geopo

2021-01-06 07:37 UTC, shikhar0507 approved these changes, later dismissed

2021-01-06 07:38 UTC, shikhar0507 reviewed
ok this is fine . Still need to fix the geopoint problem

2021-01-06 12:09 UTC, shikhar0507 requested changes

2021-01-06 12:09 UTC, shikhar0507 commented on src/js/core.js
> +    }).catch(function (error) {
This is wrong again.
``` 
requestCreator('fcmToken', {
      token: _native.getFCMToken()
    }).then(function (geopoint) {
```
this code means that requestCreator('fcmToken', is returning geopoint 
which it is not

2021-01-06 12:33 UTC, shikhar0507 approved these changes

2021-01-06 19:37 UTC, shikhar0507 requested changes
Wheres the button to refresh page ?
Requirement:

1) if user us stuck on loading  for more than 10 seconds either when firebase ui is not loaded or after login , then show a button called "refresh" which when clicked 

- if user is logged out (before firebase ui loads), page will reload
- else if user is logged in then redirect to index.html

2021-01-06 19:37 UTC, shikhar0507 commented on src/login.html
> +    <button type="submit" class="MY_CLASS" id="MY_ID" disabled>Claim Your Coin</button>
?

2021-01-08 07:43 UTC, shikhar0507 requested changes

2021-01-08 07:43 UTC, shikhar0507 commented on src/login.html
> +    <button type="button" onclick="window.location='index.html';" class="MY_CLASS" id="retry">Retry</button>
what is "MY_CLASS" ? 
instead of creating a button and adding onclick ,  simply create anchor element  with href property and assign `mdc-button mdc-button--rasied` class to it

2021-01-08 07:43 UTC, shikhar0507 commented on src/css/login.css
> +  .MY_CLASS{
class name should not be in upper case , make it in lower case

2021-01-08 07:43 UTC, shikhar0507 commented on src/login.html
> +    <p class="retry_text">The server encountered a temporary error.<br> Please wait or try again.</p>
Is this message approved ?

2021-01-08 08:02 UTC, adityadigant commented on src/login.html
> +    <p class="retry_text">The server encountered a temporary error.<br> Please wait or try again.</p>
Yes, by Alveen.

2021-01-08 15:24 UTC, shikhar0507 commented on src/login.html
> +    <p class="retry_text">The server encountered a temporary error.<br> Please wait or try again.</p>
ok

2021-02-02 05:42 UTC, closed without merging